/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumPaymentsMethodAccount } from "./EnumPaymentsMethodAccount";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PaymentListRelationFilter } from "../../payment/base/PaymentListRelationFilter";
import { EnumPaymentsMethodPaymentType } from "./EnumPaymentsMethodPaymentType";
import { EnumPaymentsMethodStatus } from "./EnumPaymentsMethodStatus";

@InputType()
class PaymentsMethodWhereInput {
  @ApiProperty({
    required: false,
    enum: EnumPaymentsMethodAccount,
  })
  @IsEnum(EnumPaymentsMethodAccount)
  @IsOptional()
  @Field(() => EnumPaymentsMethodAccount, {
    nullable: true,
  })
  account?:
    | "Bri"
    | "Mandiri"
    | "Bni"
    | "Hsbc"
    | "ShopeePay"
    | "Ovo"
    | "Gopay"
    | "Dana"
    | "Qris";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  logo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nameRef?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  noRef?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PaymentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PaymentListRelationFilter)
  @IsOptional()
  @Field(() => PaymentListRelationFilter, {
    nullable: true,
  })
  payments?: PaymentListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumPaymentsMethodPaymentType,
  })
  @IsEnum(EnumPaymentsMethodPaymentType)
  @IsOptional()
  @Field(() => EnumPaymentsMethodPaymentType, {
    nullable: true,
  })
  paymentType?: "BankTransfer" | "Ewallet";

  @ApiProperty({
    required: false,
    enum: EnumPaymentsMethodStatus,
  })
  @IsEnum(EnumPaymentsMethodStatus)
  @IsOptional()
  @Field(() => EnumPaymentsMethodStatus, {
    nullable: true,
  })
  status?: "Active" | "NonActive";
}

export { PaymentsMethodWhereInput as PaymentsMethodWhereInput };
