/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import { IsOptional, ValidateNested, IsString } from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { WeddingInvitationCommentCreateNestedManyWithoutWeddingInvitationsInput } from "./WeddingInvitationCommentCreateNestedManyWithoutWeddingInvitationsInput";
import { WeddingInvitationShareCreateNestedManyWithoutWeddingInvitationsInput } from "./WeddingInvitationShareCreateNestedManyWithoutWeddingInvitationsInput";

@InputType()
class WeddingInvitationCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  bride?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  events?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  galleries?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  gifts?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  groom?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  invites?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  moments?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  quotes?: InputJsonValue;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  userId!: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  video?: string | null;

  @ApiProperty({
    required: false,
    type: () =>
      WeddingInvitationCommentCreateNestedManyWithoutWeddingInvitationsInput,
  })
  @ValidateNested()
  @Type(
    () => WeddingInvitationCommentCreateNestedManyWithoutWeddingInvitationsInput
  )
  @IsOptional()
  @Field(
    () =>
      WeddingInvitationCommentCreateNestedManyWithoutWeddingInvitationsInput,
    {
      nullable: true,
    }
  )
  weddingInvitationComments?: WeddingInvitationCommentCreateNestedManyWithoutWeddingInvitationsInput;

  @ApiProperty({
    required: false,
    type: () =>
      WeddingInvitationShareCreateNestedManyWithoutWeddingInvitationsInput,
  })
  @ValidateNested()
  @Type(
    () => WeddingInvitationShareCreateNestedManyWithoutWeddingInvitationsInput
  )
  @IsOptional()
  @Field(
    () => WeddingInvitationShareCreateNestedManyWithoutWeddingInvitationsInput,
    {
      nullable: true,
    }
  )
  weddingInvitationShares?: WeddingInvitationShareCreateNestedManyWithoutWeddingInvitationsInput;
}

export { WeddingInvitationCreateInput as WeddingInvitationCreateInput };
