/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WeddingInvitationShareService } from "../weddingInvitationShare.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WeddingInvitationShareCreateInput } from "./WeddingInvitationShareCreateInput";
import { WeddingInvitationShare } from "./WeddingInvitationShare";
import { WeddingInvitationShareFindManyArgs } from "./WeddingInvitationShareFindManyArgs";
import { WeddingInvitationShareWhereUniqueInput } from "./WeddingInvitationShareWhereUniqueInput";
import { WeddingInvitationShareUpdateInput } from "./WeddingInvitationShareUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WeddingInvitationShareControllerBase {
  constructor(
    protected readonly service: WeddingInvitationShareService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WeddingInvitationShare })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationShare",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWeddingInvitationShare(
    @common.Body() data: WeddingInvitationShareCreateInput
  ): Promise<WeddingInvitationShare> {
    return await this.service.createWeddingInvitationShare({
      data: {
        ...data,

        weddingId: data.weddingId
          ? {
              connect: data.weddingId,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        institution: true,
        link: true,
        name: true,
        open: true,
        updatedAt: true,
        view: true,

        weddingId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WeddingInvitationShare] })
  @ApiNestedQuery(WeddingInvitationShareFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationShare",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async weddingInvitationShares(
    @common.Req() request: Request
  ): Promise<WeddingInvitationShare[]> {
    const args = plainToClass(
      WeddingInvitationShareFindManyArgs,
      request.query
    );
    return this.service.weddingInvitationShares({
      ...args,
      select: {
        createdAt: true,
        id: true,
        institution: true,
        link: true,
        name: true,
        open: true,
        updatedAt: true,
        view: true,

        weddingId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WeddingInvitationShare })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationShare",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async weddingInvitationShare(
    @common.Param() params: WeddingInvitationShareWhereUniqueInput
  ): Promise<WeddingInvitationShare | null> {
    const result = await this.service.weddingInvitationShare({
      where: params,
      select: {
        createdAt: true,
        id: true,
        institution: true,
        link: true,
        name: true,
        open: true,
        updatedAt: true,
        view: true,

        weddingId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WeddingInvitationShare })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationShare",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWeddingInvitationShare(
    @common.Param() params: WeddingInvitationShareWhereUniqueInput,
    @common.Body() data: WeddingInvitationShareUpdateInput
  ): Promise<WeddingInvitationShare | null> {
    try {
      return await this.service.updateWeddingInvitationShare({
        where: params,
        data: {
          ...data,

          weddingId: data.weddingId
            ? {
                connect: data.weddingId,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          institution: true,
          link: true,
          name: true,
          open: true,
          updatedAt: true,
          view: true,

          weddingId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WeddingInvitationShare })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationShare",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWeddingInvitationShare(
    @common.Param() params: WeddingInvitationShareWhereUniqueInput
  ): Promise<WeddingInvitationShare | null> {
    try {
      return await this.service.deleteWeddingInvitationShare({
        where: params,
        select: {
          createdAt: true,
          id: true,
          institution: true,
          link: true,
          name: true,
          open: true,
          updatedAt: true,
          view: true,

          weddingId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
