/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WeddingInvitationCommentService } from "../weddingInvitationComment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WeddingInvitationCommentCreateInput } from "./WeddingInvitationCommentCreateInput";
import { WeddingInvitationComment } from "./WeddingInvitationComment";
import { WeddingInvitationCommentFindManyArgs } from "./WeddingInvitationCommentFindManyArgs";
import { WeddingInvitationCommentWhereUniqueInput } from "./WeddingInvitationCommentWhereUniqueInput";
import { WeddingInvitationCommentUpdateInput } from "./WeddingInvitationCommentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WeddingInvitationCommentControllerBase {
  constructor(
    protected readonly service: WeddingInvitationCommentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WeddingInvitationComment })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationComment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWeddingInvitationComment(
    @common.Body() data: WeddingInvitationCommentCreateInput
  ): Promise<WeddingInvitationComment> {
    return await this.service.createWeddingInvitationComment({
      data: {
        ...data,

        weddingId: data.weddingId
          ? {
              connect: data.weddingId,
            }
          : undefined,
      },
      select: {
        address: true,
        comment: true,
        createdAt: true,
        email: true,
        id: true,
        institution: true,
        link: true,
        moment: true,
        name: true,
        phone: true,
        present: true,
        updatedAt: true,

        weddingId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WeddingInvitationComment] })
  @ApiNestedQuery(WeddingInvitationCommentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationComment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async weddingInvitationComments(
    @common.Req() request: Request
  ): Promise<WeddingInvitationComment[]> {
    const args = plainToClass(
      WeddingInvitationCommentFindManyArgs,
      request.query
    );
    return this.service.weddingInvitationComments({
      ...args,
      select: {
        address: true,
        comment: true,
        createdAt: true,
        email: true,
        id: true,
        institution: true,
        link: true,
        moment: true,
        name: true,
        phone: true,
        present: true,
        updatedAt: true,

        weddingId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WeddingInvitationComment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationComment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async weddingInvitationComment(
    @common.Param() params: WeddingInvitationCommentWhereUniqueInput
  ): Promise<WeddingInvitationComment | null> {
    const result = await this.service.weddingInvitationComment({
      where: params,
      select: {
        address: true,
        comment: true,
        createdAt: true,
        email: true,
        id: true,
        institution: true,
        link: true,
        moment: true,
        name: true,
        phone: true,
        present: true,
        updatedAt: true,

        weddingId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WeddingInvitationComment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationComment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWeddingInvitationComment(
    @common.Param() params: WeddingInvitationCommentWhereUniqueInput,
    @common.Body() data: WeddingInvitationCommentUpdateInput
  ): Promise<WeddingInvitationComment | null> {
    try {
      return await this.service.updateWeddingInvitationComment({
        where: params,
        data: {
          ...data,

          weddingId: data.weddingId
            ? {
                connect: data.weddingId,
              }
            : undefined,
        },
        select: {
          address: true,
          comment: true,
          createdAt: true,
          email: true,
          id: true,
          institution: true,
          link: true,
          moment: true,
          name: true,
          phone: true,
          present: true,
          updatedAt: true,

          weddingId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WeddingInvitationComment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeddingInvitationComment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWeddingInvitationComment(
    @common.Param() params: WeddingInvitationCommentWhereUniqueInput
  ): Promise<WeddingInvitationComment | null> {
    try {
      return await this.service.deleteWeddingInvitationComment({
        where: params,
        select: {
          address: true,
          comment: true,
          createdAt: true,
          email: true,
          id: true,
          institution: true,
          link: true,
          moment: true,
          name: true,
          phone: true,
          present: true,
          updatedAt: true,

          weddingId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
