/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { InvitationTypeCreateNestedManyWithoutUsersInput } from "./InvitationTypeCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { PaymentCreateNestedManyWithoutUsersInput } from "./PaymentCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumUserStatus } from "./EnumUserStatus";
import { WeddingInvitationCreateNestedManyWithoutUsersInput } from "./WeddingInvitationCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => InvitationTypeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvitationTypeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvitationTypeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  access?: InvitationTypeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  authenticationCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumUserStatus,
  })
  @IsEnum(EnumUserStatus)
  @IsOptional()
  @Field(() => EnumUserStatus, {
    nullable: true,
  })
  status?: "Register" | "Active" | "Nonactive" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => WeddingInvitationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WeddingInvitationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WeddingInvitationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  weddingInvitations?: WeddingInvitationCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
